server:
  port: 8300
app:
  datasource:
    credit:
      url: jdbc:mysql://docker.for.mac.localhost:3306/creditdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: inteca
      password: password
spring:
  application:
    name: credit-service
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect