eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8300
#api:
#  customer: http://localhost:8200
#  product: http://localhost:8100
app:
  datasource:
    credit:
      url: jdbc:mysql://localhost:3306/creditdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: inteca
      password: password
#customer-service:
#  ribbon:
#    listOfServers: http://localhost:8200,http://localhost:8201
#product-service:
#  ribbon:
#    listOfServers: http://localhost:8100,http://localhost:8101
spring:
  zipkin:
    base-url: http://localhost:9411/
  main:
    allow-bean-definition-overriding: true
  application:
    name: credit-service
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect